[feat] #178 recent saved link
Link-MIND/Android pull request #179
Opened 2024-10-30 18:36 UTC by leeseokchan00

## 📌 PR 요약

🌱 작업한 내용
- 홈 클립을 최근 저장한 링크로 수정

🌱 PR 포인트
-

## 📸 스크린샷

1. 첫 링크 추가

https://github.com/user-attachments/assets/e02306b9-5065-4992-aa52-dacccd4289d3

2. 링크 3개 이상 추가

https://github.com/user-attachments/assets/ab4802cc-66c9-4853-a3b3-aca1ec3c6bb4

3. 링크 삭제

https://github.com/user-attachments/assets/089c4fb3-ad6e-41f0-9f41-d2b78d60e64e

## 📮 관련 이슈
- Resolved: #178

2024-10-30 18:41 UTC, leeseokchan00 commented
아 빼먹은거 있어서 수정해야됨ㅎㅎ

2024-11-04 04:07 UTC, lsakee requested changes
CUTE

2024-11-04 04:07 UTC, lsakee commented on feature/home/src/main/java/org/sopt/home/viewholder/HomeClipViewHolder.kt
> +      if (data.categoryTitle.isNullOrEmpty()) {
fun View.setVisible(value: Boolean) {
    visibility = if (value) View.VISIBLE else View.GONE
}

2024-11-06 09:53 UTC, Sangwook123 approved these changes

2024-11-06 10:00 UTC, leeseokchan00 commented on feature/home/src/main/java/org/sopt/home/viewholder/HomeClipViewHolder.kt
> +      if (data.categoryTitle.isNullOrEmpty()) {
수정했습니다

2024-11-06 10:19 UTC, merged