Feature/#12 refactor UI
Link-MIND/Android pull request #22
Opened 2024-01-03 16:51 UTC by codingmy

## 📌 PR 요약

🌱 작업한 내용
- base activity, fragment, dialogfragment databinding에서 viewBinding으로 변환
- 네비바 커스텀 

🌱 PR 포인트
- viewBinding 참고거리 구글링이 오래걸려서 오래걸렸슴당
- 근데 dialogfragment는 참고할 거리 없이 한거라서 여기에서 잘못된거 많을수도...
- navigation bar 색상 바꾸기 전에 녹화한거라 영상에서는 bnv 배경색은 세팅전임니다

## 📸 스크린샷
|스크린샷|
|:--:|

https://github.com/Link-MIND/LinkMind-Android/assets/97686638/24a408b2-5442-4f57-bdfe-b5fb455d87bf

## 📮 관련 이슈
- Resolved: #12

2024-01-03 18:49 UTC, lsakee requested changes
네비게이션 잘했네요 !

2024-01-03 18:49 UTC, lsakee commented on core/ui/src/main/java/org/sopt/ui/base/BindingFragment.kt
> +  abstract fun getFragmentBinding(inflater: LayoutInflater, container: ViewGroup?): T
이부분 없어도 되지 않나여

2024-01-03 18:49 UTC, lsakee commented on core/ui/src/main/java/org/sopt/ui/base/BindingDialogFragment.kt
> +
이것도 필요 있?

2024-01-03 18:49 UTC, lsakee commented on core/ui/src/main/java/org/sopt/ui/base/BindingActivity.kt
> +  val bindingFactory: (LayoutInflater) -> T,
inflater 로 네이밍 정정해주세염  private 도 추가

2024-01-03 18:54 UTC, Sangwook123 commented on core/ui/src/main/java/org/sopt/ui/base/BindingFragment.kt
> +  abstract fun getFragmentBinding(inflater: LayoutInflater, container: ViewGroup?): T
bindingActivity랑 동일한 방식으로 하면 댈거같슴다

2024-01-04 05:19 UTC, CHANGEL1004 reviewed
확인했어욤 고생하셨습니다

2024-01-04 12:46 UTC, Sangwook123 approved these changes
머지합시당

2024-01-04 13:27 UTC, lsakee approved these changes
LGTM

2024-01-04 14:17 UTC, merged