Feature/#20 mypage UI
Link-MIND/Android pull request #25
Opened 2024-01-04 09:20 UTC by CHANGEL1004

## 📌 PR 요약

🌱 작업한 내용
- 마이페이지 뷰 구현

🌱 PR 포인트
- 100% 완성은 아님

## 📸 스크린샷

![스크린샷 2024-01-04 181054](https://github.com/Link-MIND/LinkMind-Android/assets/107169027/ca1fee7b-bab6-4c99-aacc-8fe9b0355961)

## 📮 관련 이슈
- Resolved: #21

2024-01-04 13:01 UTC, Sangwook123 requested changes
고생하셨슴다 리뷰 확인 바람니당!

2024-01-04 13:01 UTC, Sangwook123 commented on feature/mainfeature/build.gradle.kts
> +    implementation(project(":core:datastore"))
이거 지워주세여

2024-01-04 13:01 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/drawable/bg_mypage_line.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android">
shape 컨벤션 맞춰주세요 ~

2024-01-04 13:01 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/drawable/bg_mypage_link.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android">
얘두

2024-01-04 13:01 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/drawable/ic_count_background.xml
> +  <path
이건 어디서 쓰이고 있나요?

2024-01-04 13:01 UTC, Sangwook123 commented on gradle/libs.versions.toml
> +android-gradle-plugin = "8.2.0"
agp 버전 다시 돌려놔주세여

2024-01-04 13:01 UTC, Sangwook123 commented on gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
얘두

2024-01-04 13:01 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/layout/fragment_my.xml
> +        android:hint="@string/my_please_wait"
텍스트뷰 중앙정렬 시켜주세요

2024-01-04 13:01 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/values/strings.xml
> +  <string name="my_link_number_now">지금 까지 읽은 링크수</string>
my -> mypage가 더 나을것 같아여

2024-01-04 13:01 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/layout/fragment_my.xml
> +        style="@style/Typography.suit.regular_18"
textappearance 사용해주세요 ! 그리고 텍스트별로 컬러도 지정해주세요 ~

2024-01-04 13:02 UTC, lsakee requested changes
컨벤션 보삼

2024-01-04 13:02 UTC, lsakee commented on gradle/libs.versions.toml
> +android-gradle-plugin = "8.2.0"
요부분은 바꾸지 마세욥

2024-01-04 13:02 UTC, lsakee commented on feature/mainfeature/src/main/res/drawable/bg_mypage_link.xml
> +  <solid android:color="#F2F2F2"/>
이거 컬러에 없나유?

2024-01-04 13:02 UTC, lsakee commented on feature/mainfeature/src/main/res/drawable/bg_mypage_link.xml
> +  <solid android:color="#F2F2F2"/>
네이밍 컨벤션 맞춰주세요

2024-01-04 13:12 UTC, lsakee requested changes
레이아웃 뷰그룹 활용 더해보아요

2024-01-04 13:12 UTC, lsakee commented on feature/mainfeature/src/main/res/layout/fragment_my.xml
> +    app:layout_constraintTop_toBottomOf="@id/cl_mypage_title">
이부분 제거해주세요

2024-01-04 13:12 UTC, lsakee commented on feature/mainfeature/src/main/res/layout/fragment_my.xml
> +    app:layout_constraintTop_toTopOf="parent" />
컨스트레인트 레이아웃으로 충분히 구현 가능해 보입니다

2024-01-04 13:12 UTC, lsakee commented on feature/mainfeature/src/main/res/layout/fragment_my.xml
> +      android:layout_height="wrap_content">
요런 것들 필요 없지 않나요?

2024-01-04 13:12 UTC, lsakee commented on feature/mainfeature/src/main/res/layout/fragment_my.xml
> +      android:layout_height="match_parent">
요런 것도 공기계있으면 개발자 모드로 한번 보시면 이해가 될거 같습니다

2024-01-04 16:31 UTC, CHANGEL1004 commented on gradle/libs.versions.toml
> +android-gradle-plugin = "8.2.0"
넹

2024-01-04 16:58 UTC, CHANGEL1004 commented on feature/mainfeature/src/main/res/drawable/ic_count_background.xml
> +  <path
삭제 완

2024-01-04 17:02 UTC, CHANGEL1004 commented on gradle/libs.versions.toml
> +android-gradle-plugin = "8.2.0"
넵

2024-01-04 17:09 UTC, CHANGEL1004 commented on feature/mainfeature/src/main/res/drawable/bg_mypage_link.xml
> +  <solid android:color="#F2F2F2"/>
추가했으용

2024-01-04 18:38 UTC, Marchbreeze commented
이집 코리 야무지네요 ~~~

2024-01-05 10:19 UTC, codingmy commented on feature/mainfeature/src/main/res/layout/fragment_my.xml
> +
이 cl_mypage_title 여기서 아무것도 안 담기고 태그 닫힌거 같은데 확인부탁드려요!

2024-01-05 10:21 UTC, codingmy commented on feature/mainfeature/src/main/res/layout/fragment_my.xml
> +      android:background="#F2F2F2"
이 색상코드로 color 네임으로 넣어주면 가독성이 더 좋아질거 같아요!

2024-01-05 10:27 UTC, codingmy commented on feature/mainfeature/src/main/res/values/typography.xml
> +
이 친구는 이미지뷰 관련 스타일인가용??

2024-01-05 10:27 UTC, codingmy commented
수고하셨슴당!~!

2024-01-06 09:41 UTC, CHANGEL1004 commented on feature/mainfeature/src/main/res/values/typography.xml
> +
넹 맞아용

2024-01-06 09:41 UTC, CHANGEL1004 commented on feature/mainfeature/src/main/res/layout/fragment_my.xml
> +      android:background="#F2F2F2"
없는 줄 알았는데 있더라구여 추가했어유!~!

2024-01-06 10:48 UTC, lsakee approved these changes
LGTM

2024-01-06 12:34 UTC, Sangwook123 approved these changes
LGTM

2024-01-06 12:36 UTC, merged