Feature/#29 clip, clip detail 뷰 / UI 구현
Link-MIND/Android pull request #35
Opened 2024-01-05 07:36 UTC by codingmy

## 📌 PR 요약

🌱 작업한 내용
- clip(category)뷰, clip detail(개별 카테고리 진입시 보이는뷰)뷰 **xml 작업**

🌱 PR 포인트
삽질하다가 끊어가려고 쪼개서 pr 올리는 거라서 현재 작업 안된 부분
- 상단 툴바 구현x
- 모서리 미적용
- clip detail뷰 링크 없을 때 띄워지는 이미지 에러나서 현재 임시 이미지
- String 추출

작업한 부분
- clip뷰 리사이클러뷰 item
- clip detail뷰 리사이클러뷰 item
- 각종 margin, padding 모두 반영
- font, text 관련

네이밍 가독성을 위해 fragment 네이밍을 clip(category), clip detail(category뷰에서 특정 카테고리 진입시 링크 보여주는 뷰) 으로 변경했는데 그닥인거 같아서 좋은 아이디어 있으면 받습니다~
일단 녹화용으로 clip detail뷰를 home에 옮겨서 녹화떴슴당(커밋안함)
item 구현은 스크린샷 캡쳐 참고

+) 다시보니까 좀더 pr을 쪼개서 올렸어야했네용...담부터는 좀더 쪼개서 올리겠습니다

## 📸 스크린샷

https://github.com/Link-MIND/LinkMind-Android/assets/97686638/febf0d66-11ad-4f6d-bcd7-b25144dad8e4

|파일첨부바람|
![image](https://github.com/Link-MIND/LinkMind-Android/assets/97686638/9f11b123-c276-46ad-aaa5-713bfe5e6130)
![image](https://github.com/Link-MIND/LinkMind-Android/assets/97686638/8e0d86df-2cc9-4dd1-94fa-7e3d1b80c87f)

## 📮 관련 이슈
- Resolved: #29

2024-01-05 20:34 UTC, lsakee requested changes
svg 파일이 너무 커요 차라리 png ..

2024-01-05 20:34 UTC, lsakee commented on feature/mainfeature/src/main/res/layout/fragment_clip.xml
> +  <androidx.appcompat.widget.Toolbar
태그 닫아주세여

2024-01-05 20:34 UTC, Sangwook123 requested changes
고생하셨슴니다 리뷰 확인해주시고 스트링 추출해주세요 ~ !

2024-01-05 20:34 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/drawable/img_clip_empty.xml
이미지는 png파일로 넣어주세요

2024-01-05 20:34 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/drawable/img_link_empty.xml
얘두

2024-01-05 20:34 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/drawable/img_link_thumb.xml
얘두

2024-01-05 20:34 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/layout/fragment_clip_detail.xml
> +        android:layout_width="105dp"
dp값 지정말고 컨스트레인트 활용해 봅시다 !

2024-01-05 20:34 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/layout/fragment_clip_detail.xml
> +        android:layout_height="19dp"
얘도 0dp랑 마진으로 될거같아여

2024-01-05 20:34 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/layout/fragment_clip_detail.xml
> +        android:layout_height="38dp"
얘두

2024-01-05 20:34 UTC, Sangwook123 commented on feature/mainfeature/src/main/res/layout/fragment_clip.xml
> +  <include layout="@layout/toolbar_clip"/>
툴바안에 툴바가 들어있네여 툴바도 그냥 컨스트레인트로 만들어도 될것 같슴다

2024-01-06 09:31 UTC, codingmy commented on feature/mainfeature/src/main/res/layout/fragment_clip_detail.xml
> +        android:layout_height="38dp"
이거 첨에 마진으로 처리할려고 했었을 때 육안상 사이즈가 이상하게 나와서 길이 픽스 준거였는데 일단 다시 마진으로 해서 올릴게영

2024-01-06 10:49 UTC, lsakee approved these changes
LGTM

2024-01-06 12:34 UTC, Sangwook123 approved these changes
LGTM

2024-01-06 12:39 UTC, merged