Feature/#39 clip edit 뷰 / UI 구현
Link-MIND/Android pull request #40
Opened 2024-01-05 16:26 UTC by codingmy

## 📌 PR 요약

🌱 작업한 내용
-  툴바 적용
- 리사이클러뷰 외 ui
- 리사이클러뷰 item

🌱 PR 포인트
- 주석처리된 속성은 현재 머지 안된 브랜치에서 정의된 속성 참고 부탁드림당
- 전체 클립(마이너스, 수정이미지 없음) 이랑 사용자가 생성한 클립(마이너스, 수정이미지 있음) 둘다 하나의 item 을 사용해서 재사용성을 높이려고 하는데 나누는게 나을까요? 아니면 이대로 item 레이아웃 하나로 상황에 따라 visible 조절해서 사용하는게 좋을까요..??

## 📸 스크린샷
![image](https://github.com/Link-MIND/LinkMind-Android/assets/97686638/a11491bf-d003-4219-bdba-d27c79502d95)

## 📮 관련 이슈
- Resolved: #39

2024-01-05 20:33 UTC, lsakee requested changes
고생하셨어요

2024-01-05 20:33 UTC, lsakee commented on feature/mainfeature/src/main/res/layout/item_clip_edit_clip.xml
> +    app:layout_constraintTop_toTopOf="parent">
여기 컨스트레인트 레이아웃 쓴 이유 있나욥?

2024-01-05 20:33 UTC, lsakee commented on feature/mainfeature/src/main/res/layout/item_clip_edit_clip.xml
> +    android:orientation="horizontal"
요것도 쓰신 이유 있나요

2024-01-06 10:33 UTC, codingmy commented on feature/mainfeature/src/main/res/layout/item_clip_edit_clip.xml
> +    app:layout_constraintTop_toTopOf="parent">
여기가 기능 명세서에서 확인하면 제가 묶은 영역부분을 꾹 누르면 위치 이동이 가능하게 구성되있어서, clicklistener 달려면 해당 터치인식 영역을 layout으로 묶는게 적절하다고 생각해서 cl로 묶었어용

2024-01-06 10:35 UTC, codingmy commented on feature/mainfeature/src/main/res/layout/item_clip_edit_clip.xml
> +    android:orientation="horizontal"
이하 동문입니다~! 이 부분은 묶어준 부분 관련 속성 세팅해줬어요!

2024-01-06 10:49 UTC, lsakee approved these changes
LGTM

2024-01-06 12:35 UTC, Sangwook123 approved these changes
LGTM

2024-01-06 12:43 UTC, merged