Feature/#37 setting UI
Link-MIND/Android pull request #43
Opened 2024-01-06 09:37 UTC by CHANGEL1004

## 📌 PR 요약

🌱 작업한 내용
- setting ui
- toggle 추가

🌱 PR 포인트
-토글 기능 구현 추가해야합니다!

## 📸 스크린샷
![스크린샷 2024-01-06 183504](https://github.com/Link-MIND/LinkMind-Android/assets/107169027/a66300bd-7e23-4957-a8fb-acd7ffd52360)

## 📮 관련 이슈
- Resolved: #38

2024-01-06 09:41 UTC, lsakee requested changes
피알 빠르게 수정부탁

2024-01-06 09:41 UTC, lsakee commented on gradle/libs.versions.toml
> +androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
요거 안쓰고 지워주세요

2024-01-06 09:41 UTC, lsakee commented on feature/mainfeature/src/main/AndroidManifest.xml
> +    </activity>
요부분 수정해주세요 세팅엑티비티 프래그먼트로 전환

2024-01-06 12:36 UTC, lsakee approved these changes
LGTM

2024-01-06 12:43 UTC, merged

2024-01-18 20:38 UTC, codingmy commented on feature/mainfeature/src/main/java/org/sopt/mainfeature/settings/SettingsFragment.kt
> +      if (toasterToggle.getState() == R.id.start) View.VISIBLE else View.INVISIBLE
오 이거 어떤 코드인가요?? 무언가를 보이고 안보이게 하는 코드인거 같긴한데 무엇이 어떻게 작동하는 건지 궁금해요!

2024-01-18 20:39 UTC, codingmy commented on feature/mainfeature/src/main/java/org/sopt/mainfeature/settings/SettingsFragment.kt
> +    }
엇 여기도요!!

2024-01-18 20:40 UTC, codingmy commented on feature/mainfeature/src/main/res/values/strings.xml
> +  <string name="settings_alert">알림설정</string>
string 추출 굿입니당

2024-01-18 20:41 UTC, codingmy commented
확인했습니당