Feature/#18 timer create
Link-MIND/Android pull request #53
Opened 2024-01-07 03:21 UTC by Sangwook123

## 📌 PR 요약

🌱 작업한 내용
- 타이머 설정 플로우
- 클립지정 -> 타이머설정

🌱 PR 포인트
- 링마 화이

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

https://github.com/Link-MIND/LinkMind-Android/assets/113014331/31eb4af3-e410-4cdf-a9cc-62b366ba2dfa

## 📮 관련 이슈
- Resolved: #이슈번호

2024-01-07 09:25 UTC, lsakee requested changes
고생하셨습니다

2024-01-07 09:25 UTC, lsakee commented on feature/timer/src/main/java/org/sopt/timer/settimer/ClipSelectAdapter.kt
> +  }
그 이러면 클릭리스너가 계속 재정의 되는 거아닌가욥?

2024-01-07 09:25 UTC, lsakee commented on feature/timer/src/main/java/org/sopt/timer/settimer/ClipSelectAdapter.kt
> +  }
ViewHolder를 데이터와 연결할 때 이 메서드를 호출

2024-01-07 09:25 UTC, lsakee commented on feature/timer/src/main/java/org/sopt/timer/settimer/TextAdapter.kt
> +class TextAdapter : ListAdapter<PickerItem, PickerViewHolder>(DiffUtil) {
사소한거지만 naming이 직관적이면 좋겠습니다

2024-01-07 09:25 UTC, lsakee commented on feature/timer/src/main/java/org/sopt/timer/settimer/TimePickerFragment.kt
> +  }
그 요로직이 프래그먼트에 있어야 되나요 혹시??

2024-01-07 09:25 UTC, lsakee commented on feature/timer/src/main/java/org/sopt/timer/settimer/TimePickerFragment.kt
> +    if (adapter is NumberAdapter) recyclerView.scrollToPosition(adapter.getMiddlePosition())
위에서 사용하신 isNumber사용하시면 될거 같습니다

2024-01-07 09:25 UTC, lsakee commented on feature/timer/src/main/java/org/sopt/timer/settimer/TimePickerFragment.kt
> +            adapter.notifyDataSetChanged()
ListAdapter인데 요거 호출하신 이유있나욥?

2024-01-07 12:26 UTC, Sangwook123 commented on feature/timer/src/main/java/org/sopt/timer/settimer/ClipSelectAdapter.kt
> +  }
수정했슴니다

2024-01-07 12:26 UTC, Sangwook123 commented on feature/timer/src/main/java/org/sopt/timer/settimer/TimePickerFragment.kt
> +  }
클래스로 분리했슴니다

2024-01-07 12:27 UTC, Sangwook123 commented on feature/timer/src/main/java/org/sopt/timer/settimer/TimePickerFragment.kt
> +    if (adapter is NumberAdapter) recyclerView.scrollToPosition(adapter.getMiddlePosition())
scrollToPosition이 NumberAdapter의 함수라서 안대여 ㅜ

2024-01-07 12:28 UTC, Sangwook123 commented on feature/timer/src/main/java/org/sopt/timer/settimer/TimePickerFragment.kt
> +            adapter.notifyDataSetChanged()
저거지우면 ListAdapter 인데도 데이터 변화를 못받아주네요 해결방법은 차차 찾아보겠습니다

2024-01-07 12:38 UTC, lsakee approved these changes
LGTM

2024-01-07 12:38 UTC, merged

2024-01-18 21:32 UTC, codingmy commented on feature/timer/src/main/java/org/sopt/timer/settimer/clipselect/ClipSelectAdapter.kt
> +  private var selectedPosition = -1
초기값 세팅 좋아요 굿

2024-01-18 21:37 UTC, codingmy commented on feature/timer/src/main/java/org/sopt/timer/settimer/clipselect/ClipSelectViewHolder.kt
> +      tvItemTimerClipCount.text = "${data.count}개"
오 databinding은 제가 베이스 액티비티랑 프래그먼트에서 제거해서 이 프로젝트파일 전체에서 데이터바인딩은 못 사용하는 줄 알았는데 ViewHolder에서는 데이터바인딩을 사용할 수 있는건가요??

2024-01-18 21:40 UTC, codingmy commented on feature/timer/src/main/java/org/sopt/timer/settimer/timepicker/ListUpdater.kt
> +        val newPos = if (isNumber) pos % adapter.currentList.size else pos
오 로직 좋은거 같아요 👍

2024-01-18 21:46 UTC, codingmy reviewed
확인했슴당