Feature/#60 search result
Link-MIND/Android pull request #63
Opened 2024-01-07 18:48 UTC by CHANGEL1004

## 📌 PR 요약

🌱 작업한 내용
- search result 검색 결과 기능 구현 

🌱 PR 포인트
- ^^7

## 📸 스크린샷
|스크린샷|
|:--:|
|애뮬느림이슈로 미첨부|
## 📮 관련 이슈
- Resolved: #62

2024-01-08 19:50 UTC, lsakee requested changes
코드 통일성 지켜주세요

2024-01-08 19:50 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/SearchFragment.kt
> +class SearchFragment : Fragment() {
base Fragment로 통일성 지키기

2024-01-08 19:50 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/SearchFragment.kt
> +    _binding = null
그리고 요건 순서가 반대로 적음 베이스 쓰셈

2024-01-09 07:44 UTC, lsakee approved these changes
LGTM 저것만 바꾸고 머지 ㄱㄱ

2024-01-09 07:44 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/adapter/ClipResultAdapter.kt
> +    holder.bind(clipResult)
holder.bind(getItem(position))

2024-01-09 07:44 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/adapter/LinkResultAdapter.kt
> +    holder.bind(linkResult)
요기도

2024-01-09 14:09 UTC, lsakee approved these changes
함수화랑 네이밍 바꿔주세요

2024-01-09 14:09 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/SearchFragment.kt
> +    binding.ivLeft.setOnClickListener {
onThrottleClick 이용 core

2024-01-09 14:09 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/SearchFragment.kt
> +    )
throttleChangedListner 형식으로 딜레이 걸어주세요
필요없는 함수는 override x

2024-01-09 14:09 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/SearchFragment.kt
> +  private fun applyBoldStyling(matchingTitles: List<String>, searchTerm: String) {
함수이름이 이상해요

2024-01-09 14:09 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/SearchFragment.kt
> +}
core ui hide 이용

2024-01-09 14:09 UTC, lsakee commented on feature/mypage/src/main/res/values/strings.xml
> +    <string name="clip_title">클립명</string>
lint detekt

2024-01-09 14:09 UTC, lsakee requested changes
함수화랑 네이밍 바꿔주세요

2024-01-09 14:12 UTC, Sangwook123 commented on feature/mypage/src/main/java/org/sopt/mypage/search/viewholder/LinkResultViewHolder.kt
> +  fun bind(linkResult: LinkResultDummy) {
onBind로 통일합시다

2024-01-09 14:12 UTC, Sangwook123 commented on feature/mypage/src/main/java/org/sopt/mypage/search/SearchFragment.kt
> +            viewHolder.binding.tvClipTitle.text = spannableString
해당로직 뷰홀더로 옮겨주세요

2024-01-09 17:35 UTC, lsakee approved these changes
LGTM

2024-01-09 17:35 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/SearchFragment.kt
> +      binding.rcSearchResult.visibility = View.GONE
binding.cl!!.isVisible=true

2024-01-09 17:35 UTC, lsakee commented on feature/mypage/src/main/java/org/sopt/mypage/search/SearchViewModel.kt
> +    }
쓴이유 알아오세요

2024-01-09 17:39 UTC, merged