Feature/#81 feat click event
Link-MIND/Android pull request #83
Opened 2024-01-11 02:57 UTC by codingmy

## 📌 PR 요약

🌱 작업한 내용
- 리스트뷰에 클릭리스너 달기

🌱 PR 포인트
- 아직 머지 안한 pr에 clip edit뷰가 있어서 clip edit뷰에 있는거 빼고 clip, clip detail(link뷰) 뷰에 있는 2개 클릭리스너 달았스빈다
- 아직 머지 안한 pr에 코드들이 좀 필요해서 그냥 클릭이벤트 발생 시 해당 item id를 토스트로 띄웠습니다 아이템 클릭 시 올라오는 토스트를 봐주세요
- 산책갔다올게요

## 📸 스크린샷

https://github.com/Link-MIND/Toaster_Android/assets/97686638/4df80445-20d0-4267-a042-3a72ace37d8c

## 📮 관련 이슈
- Resolved: #81

2024-01-11 08:41 UTC, CHANGEL1004 reviewed
함수화 잘 사용하셨네여 변경사항 잘 확인했습니당

2024-01-11 08:41 UTC, CHANGEL1004 commented on feature/clip/src/main/java/org/sopt/clip/ClipViewModel.kt
왕 많다

2024-01-11 08:47 UTC, lsakee requested changes
고생쓰

2024-01-11 08:47 UTC, lsakee commented on feature/clip/src/main/java/org/sopt/clip/clip/ClipViewHolder.kt
>          root.setOnClickListener {
얼리리턴

2024-01-11 10:09 UTC, codingmy commented on feature/clip/src/main/java/org/sopt/clip/clip/ClipViewHolder.kt
>          root.setOnClickListener {
반영완

2024-01-11 13:32 UTC, Sangwook123 commented on feature/clip/src/main/java/org/sopt/clip/clip/ClipViewHolder.kt
>          root.setOnClickListener {
```suggestion
    with(binding) {
      if (clipData == null) return
      tvClipName.text = clipData.clipName
      tvClipAmount.text = clipData.clipAmount.toString() + "개"
      root.setOnClickListener 
```

2024-01-12 17:16 UTC, lsakee approved these changes
LGTM

2024-01-13 10:42 UTC, codingmy commented on feature/clip/src/main/java/org/sopt/clip/clip/ClipViewHolder.kt
>          root.setOnClickListener {
반영완

2024-01-14 11:51 UTC, merged